# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sherlog < Formula
  desc "Hypothesis-driven debugging for Claude Code — the /debug detective loop over a localhost daemon on :2218"
  homepage "https://github.com/neomodular/sherlog"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neomodular/sherlog/releases/download/v0.2.1/sherlog_0.2.1_darwin_amd64.tar.gz"
      sha256 "925e676db73677752d4b4186081211c688c71a863e89a0e8c8709066f825de40"

      define_method(:install) do
        bin.install "sherlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neomodular/sherlog/releases/download/v0.2.1/sherlog_0.2.1_darwin_arm64.tar.gz"
      sha256 "536a3de03b8cc2940eae9125c78b39deaead8c2afb2429b441eb5a6deb010645"

      define_method(:install) do
        bin.install "sherlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomodular/sherlog/releases/download/v0.2.1/sherlog_0.2.1_linux_amd64.tar.gz"
      sha256 "d20a11d0aafc7219e01e6e923df245635fcbd5a97cd6607288ba5941f5d6111a"
      define_method(:install) do
        bin.install "sherlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomodular/sherlog/releases/download/v0.2.1/sherlog_0.2.1_linux_arm64.tar.gz"
      sha256 "e867a184f7d9e96d282b8c74d02391f2adcdcba06105b84d140395c1a8e3fb2f"
      define_method(:install) do
        bin.install "sherlog"
      end
    end
  end
end
